export const styles = {
    movieListContainer: {
        maxWidth: '800px',
        margin: '20px auto',
        padding: '20px',
        backgroundColor: '#f0f0f0',
        borderRadius: '8px',
        boxShadow: '0 0 10px rgba(0, 0, 0, 0.1)',
    },
    header: {
        fontSize: '24px',
        marginBottom: '16px',
        textAlign: 'center',
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        marginBottom: '20px',
    },
    input: {
        flex: '1',
        width: '100%',
        maxWidth: '400px',
        margin: '8px',
        padding: '8px',
        fontSize: '16px',
        border: '1px solid #ccc',
        borderRadius: '4px',
        outline: 'none',
    },
    fileInputContainer: {
        display: 'flex',
        alignItems: 'center',
        marginBottom: '10px',
    },
    fileInputLabel: {
        marginRight: '10px',
        fontSize: '16px',
    },
    fileInput: {
        fontSize: '16px',
    },
    previewImage: {
        maxWidth: '100%',
        height: 'auto',
        marginTop: '10px',
        borderRadius: '4px',
    },
    button: {
        padding: '10px 20px',
        fontSize: '16px',
        backgroundColor: '#007bff',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
    movieList: {
        listStyleType: 'none',
        padding: '0',
    },
    movieListItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: '10px',
        padding: '10px',
        backgroundColor: '#fff',
        borderRadius: '4px',
        boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
    },
    posterImage: {
        width: '80px',
        height: 'auto',
        marginRight: '10px',
        borderRadius: '4px',
    },
    deleteButton: {
        padding: '6px 12px',
        fontSize: '14px',
        backgroundColor: '#dc3545',
        color: 'white',
        border: 'none',
        borderRadius: '4px',
        cursor: 'pointer',
    },
};